# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridpacket_ts.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'bridpacket_ts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62ridpacket_ts.proto\"\xb7\x01\n\x06Packet\x12\x11\n\tpacket_id\x18\x01 \x01(\x05\x12\r\n\x05proto\x18\x02 \x01(\t\x12\x0b\n\x03mac\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\x10\n\x08rssi_dbm\x18\x05 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x06 \x01(\x05\x12\r\n\x05ts_us\x18\x07 \x01(\x04\x12\x10\n\x08\x63omplete\x18\x08 \x01(\x08\x12\x12\n\nfirst_full\x18\t \x01(\x08\x12\x13\n\x04odid\x18\n \x01(\x0b\x32\x05.ODID\"z\n\x04ODID\x12\x1a\n\x08\x62\x61sic_id\x18\x01 \x03(\x0b\x32\x08.BasicID\x12\x1b\n\x08location\x18\x02 \x01(\x0b\x32\t.Location\x12\x17\n\x06system\x18\x03 \x01(\x0b\x32\x07.System\x12 \n\x0boperator_id\x18\x04 \x01(\x0b\x32\x0b.OperatorID\"J\n\x07\x42\x61sicID\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0f\n\x07ua_type\x18\x02 \x01(\x05\x12\x0f\n\x07id_type\x18\x03 \x01(\x05\x12\x0e\n\x06uas_id\x18\x04 \x01(\t\"\xbd\x01\n\x08Location\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\x12\x11\n\talt_geo_m\x18\x04 \x01(\x02\x12\x12\n\nalt_baro_m\x18\x05 \x01(\x02\x12\x10\n\x08height_m\x18\x06 \x01(\x02\x12\x13\n\x0bspeed_h_mps\x18\x07 \x01(\x02\x12\x13\n\x0bspeed_v_mps\x18\x08 \x01(\x02\x12\x0f\n\x07\x64ir_deg\x18\t \x01(\x02\x12\x13\n\x0btimestamp_s\x18\n \x01(\x02\"\x95\x01\n\x06System\x12\x14\n\x0coperator_lat\x18\x01 \x01(\x02\x12\x14\n\x0coperator_lon\x18\x02 \x01(\x02\x12\x15\n\rarea_radius_m\x18\x03 \x01(\x02\x12\x16\n\x0e\x61rea_ceiling_m\x18\x04 \x01(\x02\x12\x14\n\x0c\x61rea_floor_m\x18\x05 \x01(\x02\x12\x1a\n\x12operator_alt_geo_m\x18\x06 \x01(\x02\"!\n\nOperatorID\x12\x13\n\x0boperator_id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridpacket_ts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKET']._serialized_start=24
  _globals['_PACKET']._serialized_end=207
  _globals['_ODID']._serialized_start=209
  _globals['_ODID']._serialized_end=331
  _globals['_BASICID']._serialized_start=333
  _globals['_BASICID']._serialized_end=407
  _globals['_LOCATION']._serialized_start=410
  _globals['_LOCATION']._serialized_end=599
  _globals['_SYSTEM']._serialized_start=602
  _globals['_SYSTEM']._serialized_end=751
  _globals['_OPERATORID']._serialized_start=753
  _globals['_OPERATORID']._serialized_end=786
# @@protoc_insertion_point(module_scope)
